name: Validate PR

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Benchmark
        run: npm run benchmark
